### ISSUE TITLE
Pushing Text Into Whitespace, "Whitespace Overtype"

### ISSUE THREAD

**Issue by whaaaley** [brunetton/atom-overtype-mode#14]
So I have a sort of odd feature request. I haven't seen this done anywhere so far. The idea is to push edited text over and overtype the nearest white space to the right until reaching 0 spaces.

For example I have some jade code like this, using whitespace to keep all the items aligned. If I wanted to change the name of `Home` to `Homepage` I would have to re-align my spaces, but with "whitespace overtype", it would push text after the carret and overtype into the whitespace while leaving the rest of the line intact.

``` jade
+item('Home',          '0')(href='#home')
+item('Dashboard',     '0')(href='#dashboard')
+item('Profile',       '0')(href='#profile')
+item('Messages',      '0')(href='#messages')
+item('Notifications', '0')(href='#notifications')
+item('Compose',       '0')(href='#compose')
+item('Inbox',         '0')(href='#inbox')
+item('Sent',          '0')(href='#sent')
+item('Trash',         '0')(href='#trash')
+item('Settings',      '0')(href='#settings')
```

I couldn't find any plugins like this out there, but I thought I would take a shot at a feature request.

**Comment by Asc2011** [comment]
Hi @whaaaley ,

I've worked on this package. A status-bar-indicator, key-handling of delete- / and backspace-keypresses are done. 
You raised an interesting issue - pasting-from-clipboard, which I will work on soon. I'd like to hear your thoughts if such is still interesting to you. Or maybe you found another editor that has a overwrite-mode that you prefer now. Here I'd like to learn what makes sense in daily-task e.g. working with structured text, templates or markdown-tables.

greets Andreas

**Comment by cornelius-dol** [comment]
I would actually find that feature massively useful, since I use vertical alignment like this a lot. I don't know that I would want it as "overtype" behavior, per se, since it's actually an insertion behavior, but if something like CTL-Insert would toggle this mode, with a status bar icon to show "smart-insertion" that would be amazing. As an insert mode option, I think I would like leave this on all the time, particularly if it always inserted spaces normally, and shift-space would give you smart-insertion .

**Comment by Asc2011** [comment]
Looking at the given text-structure from the example i'd say one benefits from the the overwrite-mode right away. So overwriting and inserting new text - in a line-oriented manner - is easy. 
`Cmd`+`Shift`+`v`is 'paste-without-reformat'. I never used that one, did not even know it exists. But that way of pasting could trigger the special-case layed out in the example above. That a line-oriented overwrite/insert shall happen, preserving the structure and using the 'holes' of spaces as a region to target.
Here again, a selection e.g. of the term `Home` in order to replace it with `Homepage`resulting in
```
+item('Homepage',     '0')(href='#home')
+item('Dashboard',    '0')(href='#dashboard')
```
ok, i see what I can do here. The established overwrite-mode helps already, maybe i can improve that..
